export type UniverseStock = {
  ticker: string;
  name: string;
  sector: string;
  category: string;
  productsBlurb: string;
  howMoneyBlurb: string;
  bullBlurb: string;
  bearBlurb: string;
  teachingConcept: string;
  isBenchmark?: boolean;
};

export const STOCK_UNIVERSE: UniverseStock[] = [
  // ── Games & Toys ────────────────────────────────────────────────
  {
    ticker: "RBLX",
    name: "Roblox",
    sector: "Communication Services",
    category: "Games & Toys",
    productsBlurb: "Roblox! Adopt Me, Brookhaven, Blox Fruits, and millions of player-made games.",
    howMoneyBlurb: "Sells Robux that players spend on avatar items and game passes, and takes a cut of what creators earn.",
    bullBlurb: "Tens of millions of kids play every day, and players who grow up with Roblox may keep playing (and spending) for years.",
    bearBlurb: "It spends more money than it makes right now, and kids' tastes can change fast if a cooler game shows up.",
    teachingConcept: "Platforms & network effects",
  },
  {
    ticker: "NTDOY",
    name: "Nintendo",
    sector: "Communication Services",
    category: "Games & Toys",
    productsBlurb: "Mario, Zelda, Pokemon, Kirby, and the Nintendo Switch.",
    howMoneyBlurb: "Sells game consoles and the games that run on them, plus movies and theme park deals for its characters.",
    bullBlurb: "Nintendo owns some of the most loved characters on Earth, and only Nintendo machines can play Nintendo games.",
    bearBlurb: "Sales go up and down in big waves depending on whether a new console is hot or getting old.",
    teachingConcept: "Owning characters (intellectual property)",
  },
  {
    ticker: "MAT",
    name: "Mattel",
    sector: "Consumer Cyclical",
    category: "Games & Toys",
    productsBlurb: "Barbie, Hot Wheels, UNO, and Fisher-Price toys.",
    howMoneyBlurb: "Makes and sells toys to stores around the world, and earns extra when its characters star in movies.",
    bullBlurb: "The Barbie movie showed that old toy brands can become huge again with the right idea.",
    bearBlurb: "Kids are picking screens over toys more every year, and toy sales depend a lot on the holidays going well.",
    teachingConcept: "Brands can be reborn",
  },
  {
    ticker: "HAS",
    name: "Hasbro",
    sector: "Consumer Cyclical",
    category: "Games & Toys",
    productsBlurb: "Nerf, Monopoly, Transformers, Play-Doh, and Magic: The Gathering.",
    howMoneyBlurb: "Sells toys and games, and licenses its characters for shows, movies, and digital games.",
    bullBlurb: "Magic: The Gathering and Dungeons & Dragons have super-fans who spend a lot, year after year.",
    bearBlurb: "Regular toy sales have been shrinking, so the games business has to carry the team.",
    teachingConcept: "Fans who keep coming back",
  },
  {
    ticker: "EA",
    name: "Electronic Arts",
    sector: "Communication Services",
    category: "Games & Toys",
    productsBlurb: "EA Sports FC (soccer), Madden NFL, The Sims, and Apex Legends.",
    howMoneyBlurb: "Sells video games, plus in-game items like Ultimate Team card packs that fans buy all year long.",
    bullBlurb: "Sports games come out every single year and fans line up to buy them — that is very steady money.",
    bearBlurb: "If a big game launch goes badly or players get tired of paying for extras, profits can stumble.",
    teachingConcept: "Recurring revenue",
  },
  {
    ticker: "TTWO",
    name: "Take-Two Interactive",
    sector: "Communication Services",
    category: "Games & Toys",
    productsBlurb: "NBA 2K, Grand Theft Auto, WWE 2K, and Zynga mobile games.",
    howMoneyBlurb: "Sells blockbuster video games and in-game currency like VC in NBA 2K.",
    bullBlurb: "The next Grand Theft Auto is one of the most anticipated games ever — a single hit can bring in billions.",
    bearBlurb: "Betting on blockbusters is risky: games cost hundreds of millions to make and can get delayed for years.",
    teachingConcept: "Hit-driven businesses",
  },
  {
    ticker: "SONY",
    name: "Sony",
    sector: "Technology",
    category: "Games & Toys",
    productsBlurb: "PlayStation 5, Spider-Man and God of War games, movies, music, and headphones.",
    howMoneyBlurb: "Sells PlayStations, games, movies, and music, and makes camera chips that go inside many phones.",
    bullBlurb: "PlayStation is the best-selling console in the world, and Sony earns money from games, movies, AND music.",
    bearBlurb: "It competes with giants in every business it runs, and gadgets can have thin profits.",
    teachingConcept: "Diversification inside one company",
  },
  // ── Food & Treats ───────────────────────────────────────────────
  {
    ticker: "MCD",
    name: "McDonald's",
    sector: "Consumer Cyclical",
    category: "Food & Treats",
    productsBlurb: "Happy Meals, Big Macs, McNuggets, and fries from the golden arches.",
    howMoneyBlurb: "Mostly collects rent and fees from the local owners who run its restaurants — like a landlord for burgers.",
    bullBlurb: "Over 40,000 restaurants worldwide and people eat there in good times and bad.",
    bearBlurb: "Health trends could pull people away from fast food, and cheap menus make it hard to raise prices.",
    teachingConcept: "The franchise model",
  },
  {
    ticker: "HSY",
    name: "Hershey",
    sector: "Consumer Defensive",
    category: "Food & Treats",
    productsBlurb: "Hershey's bars, Reese's, Kit Kat (in the US), Jolly Ranchers, and Twizzlers.",
    howMoneyBlurb: "Makes candy and snacks and sells them in nearly every store in America.",
    bullBlurb: "People buy chocolate every year no matter what the economy is doing — especially on Halloween.",
    bearBlurb: "Cocoa prices have gotten very expensive, which squeezes how much profit each candy bar makes.",
    teachingConcept: "Steady demand (defensive stocks)",
  },
  {
    ticker: "KO",
    name: "Coca-Cola",
    sector: "Consumer Defensive",
    category: "Food & Treats",
    productsBlurb: "Coke, Sprite, Fanta, Powerade, Minute Maid, and Dasani water.",
    howMoneyBlurb: "Sells drink syrup and brands to bottlers around the world who make and deliver the drinks.",
    bullBlurb: "One of the most famous brands ever, sold in almost every country, and it has paid shareholders a dividend for over 100 years.",
    bearBlurb: "People are drinking less sugary soda, so Coke has to keep inventing new drinks to grow.",
    teachingConcept: "Brand moat & dividends",
  },
  {
    ticker: "DPZ",
    name: "Domino's Pizza",
    sector: "Consumer Cyclical",
    category: "Food & Treats",
    productsBlurb: "Pizza night! Domino's delivery, the pizza tracker, and cheesy bread.",
    howMoneyBlurb: "Collects fees from local franchise owners and sells them ingredients and supplies.",
    bullBlurb: "Domino's treats itself like a tech company — its app and delivery tracking keep customers ordering again and again.",
    bearBlurb: "Delivery apps like DoorDash and lots of pizza rivals mean the competition never sleeps.",
    teachingConcept: "Technology inside an old business",
  },
  {
    ticker: "CMG",
    name: "Chipotle",
    sector: "Consumer Cyclical",
    category: "Food & Treats",
    productsBlurb: "Burritos, burrito bowls, chips and guac.",
    howMoneyBlurb: "Owns all of its restaurants and keeps the profit from every burrito it sells.",
    bullBlurb: "Lines out the door, prices people happily pay, and thousands of new locations still to open.",
    bearBlurb: "The stock is priced like everything will go perfectly — any stumble (like a food safety scare) can hit it hard.",
    teachingConcept: "Growth stocks & expectations",
  },
  {
    ticker: "YUM",
    name: "Yum! Brands",
    sector: "Consumer Cyclical",
    category: "Food & Treats",
    productsBlurb: "Taco Bell, KFC, and Pizza Hut — all one company!",
    howMoneyBlurb: "Collects royalty fees from franchise owners running its restaurants in over 150 countries.",
    bullBlurb: "Three famous brands and huge growth in other countries, with the franchise model keeping profits steady.",
    bearBlurb: "Fast-food competition is brutal, and Pizza Hut has been the slow runner of the three brands.",
    teachingConcept: "Royalties",
  },
  {
    ticker: "SBUX",
    name: "Starbucks",
    sector: "Consumer Cyclical",
    category: "Food & Treats",
    productsBlurb: "Frappuccinos, cake pops, pink drinks, and the cups everyone carries.",
    howMoneyBlurb: "Sells coffee and treats in about 40,000 stores, with the app and rewards program keeping people coming back.",
    bullBlurb: "Coffee is a daily habit, and Starbucks rewards members reload billions of dollars onto the app before they even order.",
    bearBlurb: "Lines got slow and drinks got pricey, so it's spending big to win grumpy customers back.",
    teachingConcept: "Habits & loyalty programs",
  },
  {
    ticker: "PEP",
    name: "PepsiCo",
    sector: "Consumer Defensive",
    category: "Food & Treats",
    productsBlurb: "Pepsi, Gatorade, Doritos, Cheetos, Lay's, and Cap'n Crunch.",
    howMoneyBlurb: "Sells drinks AND snacks — Frito-Lay chips are actually its biggest moneymaker.",
    bullBlurb: "Own the whole snack aisle: even when one brand slows down, twenty others keep selling.",
    bearBlurb: "Health trends and weight-loss drugs could shrink how many chips and sodas people buy.",
    teachingConcept: "A portfolio of brands",
  },
  {
    ticker: "CELH",
    name: "Celsius Holdings",
    sector: "Consumer Defensive",
    category: "Food & Treats",
    productsBlurb: "The shiny Celsius energy drink cans in every gym bag and gas station.",
    howMoneyBlurb: "Sells fitness energy drinks, with Pepsi helping deliver them to stores everywhere.",
    bullBlurb: "It went from unknown to one of America's top energy drinks in just a few years.",
    bearBlurb: "Drink fads can fizzle — if the next cool can comes along, growth can stop fast.",
    teachingConcept: "Fads vs. lasting trends",
  },
  // ── Entertainment ───────────────────────────────────────────────
  {
    ticker: "DIS",
    name: "Disney",
    sector: "Communication Services",
    category: "Entertainment",
    productsBlurb: "Disney World, Marvel, Star Wars, Pixar, Frozen, and Disney+.",
    howMoneyBlurb: "Makes money from theme parks, movies, Disney+ subscriptions, ESPN, and mountains of merchandise.",
    bullBlurb: "Disney is like a team of famous players — Mickey, Marvel, and Star Wars — that it can use in parks, movies, and toys all at once.",
    bearBlurb: "Streaming is hard to make profitable, movies can flop, and park tickets are getting really expensive.",
    teachingConcept: "Intellectual property",
  },
  {
    ticker: "NFLX",
    name: "Netflix",
    sector: "Communication Services",
    category: "Entertainment",
    productsBlurb: "Stranger Things, Wednesday, KPop Demon Hunters, and endless movie nights.",
    howMoneyBlurb: "Collects a monthly subscription from hundreds of millions of homes, plus money from ads.",
    bullBlurb: "It won the streaming wars — more subscribers than anyone, and it keeps making shows the whole world watches.",
    bearBlurb: "Making shows costs billions every year, and everyone from Disney to YouTube is fighting for screen time.",
    teachingConcept: "Subscriptions",
  },
  {
    ticker: "SPOT",
    name: "Spotify",
    sector: "Communication Services",
    category: "Entertainment",
    productsBlurb: "Music, playlists, podcasts, and Spotify Wrapped every December.",
    howMoneyBlurb: "Sells Premium subscriptions and plays ads to free listeners, paying artists from that money.",
    bullBlurb: "The biggest music app in the world, and people almost never cancel their music subscription.",
    bearBlurb: "It has to pay most of its money to record labels, so keeping a big profit is genuinely hard.",
    teachingConcept: "Margins (what you keep from each dollar)",
  },
  {
    ticker: "WBD",
    name: "Warner Bros. Discovery",
    sector: "Communication Services",
    category: "Entertainment",
    productsBlurb: "Harry Potter, Batman, Scooby-Doo, Cartoon Network, and HBO Max.",
    howMoneyBlurb: "Makes money from movies, TV channels, and streaming subscriptions.",
    bullBlurb: "It owns legendary characters and stories, and the stock is priced cheaply if things turn around.",
    bearBlurb: "The company borrowed a LOT of money, and old-style cable TV is shrinking every year.",
    teachingConcept: "Debt",
  },
  {
    ticker: "FUN",
    name: "Six Flags Entertainment",
    sector: "Consumer Cyclical",
    category: "Entertainment",
    productsBlurb: "Six Flags and Cedar Point — roller coasters, water parks, and funnel cake.",
    howMoneyBlurb: "Sells park tickets and season passes, then earns more inside on food, drinks, and fast-lane passes.",
    bullBlurb: "It owns more than 40 parks, and thrill seekers show up every summer — the ticker is literally FUN.",
    bearBlurb: "Parks sit mostly empty all winter, rainy summers hurt, and the company carries a lot of debt.",
    teachingConcept: "Seasonal businesses",
  },
  // ── Tech They Use ───────────────────────────────────────────────
  {
    ticker: "AAPL",
    name: "Apple",
    sector: "Technology",
    category: "Tech They Use",
    productsBlurb: "iPhone, iPad, Mac, AirPods, Apple Watch, and the App Store.",
    howMoneyBlurb: "Sells devices, then earns steady fees from the App Store, iCloud, Apple Music, and more.",
    bullBlurb: "Once people buy an iPhone they usually stay with Apple forever — and pay for services every month.",
    bearBlurb: "The iPhone is most of the business, so Apple needs its next big thing eventually.",
    teachingConcept: "Ecosystems & switching costs",
  },
  {
    ticker: "GOOGL",
    name: "Alphabet (Google)",
    sector: "Communication Services",
    category: "Tech They Use",
    productsBlurb: "Google Search, YouTube, Chromebooks, Google Maps, and Android phones.",
    howMoneyBlurb: "Shows ads next to searches and YouTube videos — billions of them every day.",
    bullBlurb: "Almost everyone on the internet uses Google or YouTube daily, and it is a leader in AI.",
    bearBlurb: "AI chatbots could change how people search, and governments keep suing Google over its power.",
    teachingConcept: "Advertising business models",
  },
  {
    ticker: "MSFT",
    name: "Microsoft",
    sector: "Technology",
    category: "Tech They Use",
    productsBlurb: "Xbox, Minecraft, Windows, Word and PowerPoint, and the Copilot AI.",
    howMoneyBlurb: "Sells software subscriptions to businesses and schools, cloud computing power, and Xbox games.",
    bullBlurb: "Nearly every company on Earth pays Microsoft every month, and its cloud powers much of the AI boom.",
    bearBlurb: "It is spending gigantic amounts building AI data centers, and that bet has to pay off.",
    teachingConcept: "Business customers (B2B)",
  },
  {
    ticker: "AMZN",
    name: "Amazon",
    sector: "Consumer Cyclical",
    category: "Tech They Use",
    productsBlurb: "Amazon boxes on the doorstep, Prime Video, Alexa, and Kindle.",
    howMoneyBlurb: "Sells almost everything online, collects Prime subscriptions, and rents computing power to other companies (AWS).",
    bullBlurb: "The everything store plus AWS, its cloud business, which quietly earns most of the profit.",
    bearBlurb: "Delivering millions of packages is expensive, and regulators watch Amazon closely.",
    teachingConcept: "Scale (being the biggest)",
  },
  {
    ticker: "META",
    name: "Meta Platforms",
    sector: "Communication Services",
    category: "Tech They Use",
    productsBlurb: "Instagram, WhatsApp, Facebook, and Quest VR headsets.",
    howMoneyBlurb: "Shows ads to the billions of people using its apps every day.",
    bullBlurb: "More than 3 billion people use a Meta app daily — advertisers cannot ignore that.",
    bearBlurb: "Young people drift to new apps, and Meta spends billions on VR and AI bets that may not pay off.",
    teachingConcept: "Attention is the product",
  },
  {
    ticker: "SNAP",
    name: "Snap (Snapchat)",
    sector: "Communication Services",
    category: "Tech They Use",
    productsBlurb: "Snapchat streaks, filters, Bitmoji, and the Snap Map.",
    howMoneyBlurb: "Shows ads between snaps and stories, and sells Snapchat+ subscriptions.",
    bullBlurb: "Hundreds of millions of young people open Snapchat every single day — that attention is valuable.",
    bearBlurb: "It fights giants like Instagram and TikTok for ad money and still struggles to turn a real profit.",
    teachingConcept: "Users vs. profits",
  },
  {
    ticker: "DUOL",
    name: "Duolingo",
    sector: "Technology",
    category: "Tech They Use",
    productsBlurb: "The green owl that guilt-trips you into practicing Spanish every day.",
    howMoneyBlurb: "The app is free with ads; superfans pay for Super Duolingo to skip ads and get extra hearts.",
    bullBlurb: "Streaks and leaderboards make learning feel like a game, and tens of millions play daily.",
    bearBlurb: "AI translators keep getting better, and most users never pay a cent.",
    teachingConcept: "Freemium (free + premium)",
  },
  // ── Sports & Style ──────────────────────────────────────────────
  {
    ticker: "NKE",
    name: "Nike",
    sector: "Consumer Cyclical",
    category: "Sports & Style",
    productsBlurb: "Air Jordans, Air Force 1s, soccer cleats, and the swoosh on every field.",
    howMoneyBlurb: "Designs shoes and clothes, has them made by factories, and sells them worldwide at a markup.",
    bullBlurb: "The most famous sports brand on Earth, worn by the best athletes in every sport.",
    bearBlurb: "Trendy rivals like Hoka and On are stealing fans, and sneaker fashion changes fast.",
    teachingConcept: "Brand power",
  },
  {
    ticker: "LULU",
    name: "Lululemon",
    sector: "Consumer Cyclical",
    category: "Sports & Style",
    productsBlurb: "Leggings, hoodies, and the belt bags everyone wears.",
    howMoneyBlurb: "Sells its own athletic clothes in its own stores and online — no middleman.",
    bullBlurb: "Fans pay full price and keep coming back, which makes each sale extra profitable.",
    bearBlurb: "Fashion is fickle — cheaper copycats are everywhere, and cool can fade.",
    teachingConcept: "Pricing power",
  },
  {
    ticker: "FL",
    name: "Foot Locker",
    sector: "Consumer Cyclical",
    category: "Sports & Style",
    productsBlurb: "The sneaker store at the mall with the referee-stripe uniforms.",
    howMoneyBlurb: "Buys sneakers from brands like Nike and sells them in its stores for more than it paid.",
    bullBlurb: "If sneaker culture stays hot and malls bounce back, a cheap stock could recover a lot.",
    bearBlurb: "Nike now sells straight to customers online, skipping stores like Foot Locker entirely.",
    teachingConcept: "The middleman problem",
  },
  {
    ticker: "DKS",
    name: "Dick's Sporting Goods",
    sector: "Consumer Cyclical",
    category: "Sports & Style",
    productsBlurb: "Bats, cleats, basketballs, and giant stores full of sports gear.",
    howMoneyBlurb: "Sells sports equipment and clothing in big stores, including giant 'House of Sport' locations.",
    bullBlurb: "Youth sports keep growing, and its huge experience stores (with rock walls and batting cages) pull families in.",
    bearBlurb: "When families cut spending, new gear is an easy thing to skip; online shopping is tough competition.",
    teachingConcept: "Economic cycles",
  },
  {
    ticker: "CROX",
    name: "Crocs",
    sector: "Consumer Cyclical",
    category: "Sports & Style",
    productsBlurb: "Crocs in every color, Jibbitz charms, and sport mode.",
    howMoneyBlurb: "Sells foam clogs and sandals worldwide, plus the little Jibbitz charms that personalize them.",
    bullBlurb: "Crocs went from 'ugly shoe' joke to must-have — and each pair is cheap to make, so profits are chunky.",
    bearBlurb: "Fashion is fickle: if Crocs stop being cool again, sales can sink fast (it happened once before).",
    teachingConcept: "Riding a trend",
  },
  {
    ticker: "ELF",
    name: "e.l.f. Beauty",
    sector: "Consumer Defensive",
    category: "Sports & Style",
    productsBlurb: "The affordable makeup and skincare all over TikTok — plus Rhode, the brand it bought from Hailey Bieber.",
    howMoneyBlurb: "Sells low-priced makeup in Target and drugstores, using viral social media instead of expensive ads.",
    bullBlurb: "It grew sales for over 20 quarters in a row by giving tweens and teens designer-style products at pocket-money prices.",
    bearBlurb: "Beauty trends move at TikTok speed, and bigger brands can copy its best products and prices.",
    teachingConcept: "Going viral as marketing",
  },
  // ── Rides & Travel ──────────────────────────────────────────────
  {
    ticker: "TSLA",
    name: "Tesla",
    sector: "Consumer Cyclical",
    category: "Rides & Travel",
    productsBlurb: "Electric cars with giant screens, the Cybertruck, and self-driving tech.",
    howMoneyBlurb: "Sells electric cars, batteries, and solar gear, and charges for its self-driving software.",
    bullBlurb: "Fans believe Tesla is really a robot and AI company — self-driving taxis could change everything.",
    bearBlurb: "The stock's price already assumes big dreams come true, and rivals' electric cars get better every year.",
    teachingConcept: "Story stocks & valuation",
  },
  {
    ticker: "F",
    name: "Ford",
    sector: "Consumer Cyclical",
    category: "Rides & Travel",
    productsBlurb: "F-150 pickup trucks, Mustangs, and Broncos.",
    howMoneyBlurb: "Builds and sells cars and trucks, and earns money lending people cash to buy them.",
    bullBlurb: "The F-150 has been America's best-selling truck for over 40 years, and the stock pays a nice dividend.",
    bearBlurb: "Making cars is expensive and competitive, and Ford has lost billions on electric vehicles so far.",
    teachingConcept: "Old economy vs. new economy",
  },
  {
    ticker: "UBER",
    name: "Uber",
    sector: "Technology",
    category: "Rides & Travel",
    productsBlurb: "Tap a button, a car shows up. Plus Uber Eats bringing dinner.",
    howMoneyBlurb: "Takes a cut of every ride and every food delivery booked through its app.",
    bullBlurb: "The biggest ride network in the world — more riders attract more drivers, which attracts more riders.",
    bearBlurb: "Robotaxis could be a friend or an enemy, and drivers' pay rules could change the math.",
    teachingConcept: "Marketplaces",
  },
  {
    ticker: "DAL",
    name: "Delta Air Lines",
    sector: "Industrials",
    category: "Rides & Travel",
    productsBlurb: "Vacation flights, window seats, and those little pretzels.",
    howMoneyBlurb: "Sells plane tickets, and earns a surprising amount from its credit card partnership with American Express.",
    bullBlurb: "People love to travel more than ever, and Delta is the best-run big airline in America.",
    bearBlurb: "Fuel prices, storms, and recessions can wreck an airline's profits fast.",
    teachingConcept: "High fixed costs",
  },
  {
    ticker: "RCL",
    name: "Royal Caribbean",
    sector: "Consumer Cyclical",
    category: "Rides & Travel",
    productsBlurb: "Giant cruise ships with waterslides, ice rinks, and their own private island.",
    howMoneyBlurb: "Sells cruise tickets, then earns even more onboard from food, drinks, and excursions.",
    bullBlurb: "Ships are sailing full, and the newest mega-ships (like Icon of the Seas) are booked way ahead.",
    bearBlurb: "Cruise lines carry big debts, and a recession or scare could empty the ships.",
    teachingConcept: "Operating leverage",
  },
  // ── Stores ──────────────────────────────────────────────────────
  {
    ticker: "WMT",
    name: "Walmart",
    sector: "Consumer Defensive",
    category: "Stores",
    productsBlurb: "Superstores with groceries, toys, games, and everything else.",
    howMoneyBlurb: "Sells huge amounts of everyday stuff at low prices, making a little profit on each item, millions of times a day.",
    bullBlurb: "The biggest retailer on Earth keeps winning online too — everyone shops there in good times and bad.",
    bearBlurb: "Profits per item are tiny, so it must run perfectly to keep growing.",
    teachingConcept: "Volume over margin",
  },
  {
    ticker: "TGT",
    name: "Target",
    sector: "Consumer Defensive",
    category: "Stores",
    productsBlurb: "The red bullseye store — toys, clothes, snacks, and the dollar section.",
    howMoneyBlurb: "Sells stylish-but-affordable everything in its stores and through same-day pickup.",
    bullBlurb: "Families love Target's own brands, which earn better profits than selling other companies' stuff.",
    bearBlurb: "It sells more 'fun stuff' than Walmart, so when wallets tighten, Target feels it first.",
    teachingConcept: "Private-label brands",
  },
  {
    ticker: "COST",
    name: "Costco",
    sector: "Consumer Defensive",
    category: "Stores",
    productsBlurb: "Giant carts, free samples, the $1.50 hot dog combo, and bulk everything.",
    howMoneyBlurb: "Makes most of its profit from membership fees — the warehouse prices are kept near cost on purpose.",
    bullBlurb: "Members renew over 90% of the time, making Costco's profits incredibly reliable.",
    bearBlurb: "The stock is expensive because everyone already knows Costco is great.",
    teachingConcept: "The membership model",
  },
  {
    ticker: "FIVE",
    name: "Five Below",
    sector: "Consumer Cyclical",
    category: "Stores",
    productsBlurb: "The store where (almost) everything is $5 or less — squishies, candy, phone cases, and fidget toys.",
    howMoneyBlurb: "Buys trendy stuff cheap and sells it to tweens and teens at pocket-money prices.",
    bullBlurb: "It is built for kids' allowances, jumps on every trend fast, and keeps opening hundreds of new stores.",
    bearBlurb: "Cheap-stuff rivals like Temu and dollar stores fight for the same wallets, and higher costs squeeze those low prices.",
    teachingConcept: "Knowing your customer",
  },
  {
    ticker: "HD",
    name: "Home Depot",
    sector: "Consumer Cyclical",
    category: "Stores",
    productsBlurb: "The giant orange store with lumber, tools, paint, and the racecar shopping carts.",
    howMoneyBlurb: "Sells home-improvement supplies to families fixing up houses and to professional builders.",
    bullBlurb: "Houses always need fixing, and pros buying supplies every week make sales steady.",
    bearBlurb: "When it's expensive to borrow money, people delay moving and big projects — and Home Depot feels it.",
    teachingConcept: "Housing cycles",
  },
  // ── Animals & Health ────────────────────────────────────────────
  {
    ticker: "CHWY",
    name: "Chewy",
    sector: "Consumer Cyclical",
    category: "Animals & Health",
    productsBlurb: "Dog food, cat toys, and pet supplies delivered in the smiley box.",
    howMoneyBlurb: "Sells pet food and supplies online, mostly through auto-ship subscriptions that repeat every month.",
    bullBlurb: "Pets eat every day! Most sales are auto-ship, which means super-predictable revenue.",
    bearBlurb: "Amazon and Walmart sell pet food too, and shipping heavy dog food bags is costly.",
    teachingConcept: "Repeat purchases",
  },
  {
    ticker: "IDXX",
    name: "IDEXX Laboratories",
    sector: "Healthcare",
    category: "Animals & Health",
    productsBlurb: "The lab machines at the vet that run your pet's health tests.",
    howMoneyBlurb: "Sells testing machines to vets, then keeps selling the test kits those machines need forever.",
    bullBlurb: "People treat pets like family and spend more on vet care every year — and every test uses IDEXX supplies.",
    bearBlurb: "Vet visits dip when money is tight, and the stock is priced for excellence.",
    teachingConcept: "Razor and blades model",
  },
  {
    ticker: "JNJ",
    name: "Johnson & Johnson",
    sector: "Healthcare",
    category: "Animals & Health",
    productsBlurb: "Band-Aids' old parent company — now focused on medicines and medical devices that fix people up.",
    howMoneyBlurb: "Sells prescription medicines and surgical tools to hospitals and patients worldwide.",
    bullBlurb: "People need medicine no matter what, and J&J has raised its dividend every year for over 60 years.",
    bearBlurb: "Drugs lose their patents over time, so it must keep inventing new ones; lawsuits are a constant risk.",
    teachingConcept: "Dividend aristocrats",
  },
  // ── Grown-Up Picks ──────────────────────────────────────────────
  {
    ticker: "BRK-B",
    name: "Berkshire Hathaway",
    sector: "Financial Services",
    category: "Grown-Up Picks",
    productsBlurb: "Warren Buffett's company — it owns GEICO, Duracell, Dairy Queen, and big pieces of Apple and Coke.",
    howMoneyBlurb: "Owns dozens of whole companies and giant piles of stocks, collecting all their profits.",
    bullBlurb: "It is like buying a ready-made portfolio picked by the most famous investor ever.",
    bearBlurb: "It is so big now that growing fast is hard, and Buffett is in his 90s.",
    teachingConcept: "Compounding",
  },
  {
    ticker: "V",
    name: "Visa",
    sector: "Financial Services",
    category: "Grown-Up Picks",
    productsBlurb: "The Visa logo on the card grown-ups tap to pay for everything.",
    howMoneyBlurb: "Takes a tiny fee every time anyone, anywhere, pays with a Visa card — trillions of times a year.",
    bullBlurb: "Visa earns a sliver of nearly every purchase on Earth without lending any money itself.",
    bearBlurb: "Governments want payment fees lower, and new pay apps could someday route around the card networks.",
    teachingConcept: "Network effects",
  },
  // ── Big Machines ────────────────────────────────────────────────
  {
    ticker: "DE",
    name: "John Deere",
    sector: "Industrials",
    category: "Big Machines",
    productsBlurb: "The green tractors and combines on every farm.",
    howMoneyBlurb: "Sells tractors and farm machines, plus smart-farming software subscriptions farmers pay for yearly.",
    bullBlurb: "The world always needs food, and Deere's self-driving tractors are real robots working today.",
    bearBlurb: "When crop prices fall, farmers stop buying new tractors — sales move in big cycles.",
    teachingConcept: "Cyclical industries",
  },
  {
    ticker: "CAT",
    name: "Caterpillar",
    sector: "Industrials",
    category: "Big Machines",
    productsBlurb: "The giant yellow diggers, bulldozers, and dump trucks at every construction site.",
    howMoneyBlurb: "Sells construction and mining machines through dealers worldwide, plus parts and repairs for decades after.",
    bullBlurb: "Roads, bridges, mines, and data centers all need big yellow machines — and worn-out parts mean repeat sales forever.",
    bearBlurb: "When building slows down, companies stop ordering million-dollar machines in a hurry.",
    teachingConcept: "Selling parts & service",
  },
  {
    ticker: "WM",
    name: "Waste Management",
    sector: "Industrials",
    category: "Big Machines",
    productsBlurb: "The green garbage and recycling trucks that rumble down your street every week.",
    howMoneyBlurb: "Charges homes, businesses, and cities steady fees to haul trash, and owns the landfills where it goes.",
    bullBlurb: "Trash never takes a day off, and it's nearly impossible for a rival to build new landfills next door.",
    bearBlurb: "Trucks, fuel, and workers keep getting more expensive, and growth is slow and steady, not exciting.",
    teachingConcept: "Boring can be beautiful",
  },
  {
    ticker: "UPS",
    name: "UPS",
    sector: "Industrials",
    category: "Big Machines",
    productsBlurb: "The brown trucks and boxes delivering packages to your door.",
    howMoneyBlurb: "Charges businesses and shoppers to move millions of packages a day through its planes, hubs, and trucks.",
    bullBlurb: "Online shopping keeps growing, and building a delivery network this big would take a rival decades.",
    bearBlurb: "Amazon delivers more of its own boxes now, and planes, trucks, and drivers cost a fortune to run.",
    teachingConcept: "Logistics networks",
  },
  // ── Space & Sky ─────────────────────────────────────────────────
  {
    ticker: "RKLB",
    name: "Rocket Lab",
    sector: "Industrials",
    category: "Space & Sky",
    productsBlurb: "Real rockets! Rocket Lab launches satellites to space almost every month.",
    howMoneyBlurb: "Charges companies and governments to launch satellites, and builds satellite parts and spacecraft for them too.",
    bullBlurb: "SpaceX is private — you can't buy its stock — so Rocket Lab is one of the only real rocket companies anyone can own, and its bigger Neutron rocket is coming.",
    bearBlurb: "Rockets are hard: launches can fail, the company isn't profitable yet, and SpaceX is a giant competitor.",
    teachingConcept: "Public vs. private companies",
  },
  {
    ticker: "BA",
    name: "Boeing",
    sector: "Industrials",
    category: "Space & Sky",
    productsBlurb: "The 737 and 787 jets you've probably flown on, plus fighter jets and spacecraft.",
    howMoneyBlurb: "Sells airplanes to airlines with years-long waiting lists, plus defense and space work for governments.",
    bullBlurb: "Only two companies on Earth build big passenger jets, and Boeing's order book stretches years into the future.",
    bearBlurb: "Safety problems and factory delays have cost it billions and its reputation needs repairs too.",
    teachingConcept: "Duopolies (two big rivals)",
  },
  {
    ticker: "LMT",
    name: "Lockheed Martin",
    sector: "Industrials",
    category: "Space & Sky",
    productsBlurb: "F-35 fighter jets, helicopters, satellites, and NASA spacecraft parts.",
    howMoneyBlurb: "Builds jets, missiles, and space systems, mostly under long contracts with the US government.",
    bullBlurb: "Its biggest customer is the US government, which signs contracts lasting decades and always pays its bills.",
    bearBlurb: "Depending on one giant customer means budget fights in Washington can hit sales.",
    teachingConcept: "Government customers",
  },
  {
    ticker: "GE",
    name: "GE Aerospace",
    sector: "Industrials",
    category: "Space & Sky",
    productsBlurb: "The jet engines hanging under the wings of most planes you see.",
    howMoneyBlurb: "Sells jet engines, then earns for decades servicing and repairing every engine it ever sold.",
    bullBlurb: "Engines fly for 30+ years and must be serviced by the maker — sell one engine, get paid for a generation.",
    bearBlurb: "If people fly less or plane factories slow down, engine orders and service hours drop too.",
    teachingConcept: "The aftermarket (service revenue)",
  },
  // ── AI & Big Compute ────────────────────────────────────────────
  {
    ticker: "NVDA",
    name: "NVIDIA",
    sector: "Technology",
    category: "AI & Big Compute",
    productsBlurb: "The graphics chips in gaming PCs — and the AI chips every tech giant is racing to buy.",
    howMoneyBlurb: "Designs the most powerful computer chips in the world and sells them for enormous profits.",
    bullBlurb: "Every company building AI needs NVIDIA chips, and there aren't enough to go around.",
    bearBlurb: "If the AI building boom slows, or customers build their own chips, the party could quiet down fast.",
    teachingConcept: "Selling shovels in a gold rush",
  },
  {
    ticker: "AMD",
    name: "AMD",
    sector: "Technology",
    category: "AI & Big Compute",
    productsBlurb: "The chips inside the PlayStation 5 and Xbox, plus processors in lots of gaming PCs.",
    howMoneyBlurb: "Designs computer chips for game consoles, laptops, and the data centers that run AI.",
    bullBlurb: "Everyone buying AI chips wants a second choice besides NVIDIA — and AMD is the clear number two, hungry to catch up.",
    bearBlurb: "NVIDIA is far ahead in AI chips, and big customers like Google and Amazon are designing chips of their own.",
    teachingConcept: "Challenger vs. champion",
  },
  {
    ticker: "ORCL",
    name: "Oracle",
    sector: "Technology",
    category: "AI & Big Compute",
    productsBlurb: "You don't see Oracle, but grown-ups' companies run on it — and it builds giant computer warehouses that rent brainpower to the world.",
    howMoneyBlurb: "Sells the software big companies use to store their information, and rents out computing power from its data centers (its cloud).",
    bullBlurb: "AI companies have promised Oracle hundreds of billions of dollars to rent its computer warehouses for years to come.",
    bearBlurb: "It has to spend gigantic amounts building those warehouses first — and its customers have to stay rich enough to pay the rent.",
    teachingConcept: "Backlog (promised future sales)",
  },
  {
    ticker: "CRWV",
    name: "CoreWeave",
    sector: "Technology",
    category: "AI & Big Compute",
    productsBlurb: "Nothing you can buy! CoreWeave builds special gyms packed with NVIDIA chips where AI goes to train.",
    howMoneyBlurb: "Rents time on its AI supercomputers to companies like Microsoft and OpenAI, usually on long contracts.",
    bullBlurb: "The world wants way more AI computing than exists, and CoreWeave is one of the fastest builders of it.",
    bearBlurb: "Most of its money comes from just a few giant customers, and it borrowed billions to buy all those chips.",
    teachingConcept: "Customer concentration",
  },
  {
    ticker: "NBIS",
    name: "Nebius",
    sector: "Technology",
    category: "AI & Big Compute",
    productsBlurb: "Another AI gym builder — data centers full of NVIDIA chips that AI companies rent by the hour.",
    howMoneyBlurb: "Rents out AI computing power and tools to companies training and running AI models.",
    bullBlurb: "It is growing incredibly fast, NVIDIA itself invested in it, and Microsoft signed a deal worth billions to rent its computers.",
    bearBlurb: "It races much bigger rivals and must spend fortunes on chips and buildings before the rent money rolls in.",
    teachingConcept: "Capacity vs. demand",
  },
  {
    ticker: "PLTR",
    name: "Palantir",
    sector: "Technology",
    category: "AI & Big Compute",
    productsBlurb: "Secret-agent-sounding AI software that helps governments and big companies make sense of mountains of data.",
    howMoneyBlurb: "Sells expensive software subscriptions to governments, the military, and huge companies.",
    bullBlurb: "Its AI platform is spreading fast through businesses, and government contracts run for years.",
    bearBlurb: "The stock trades at one of the highest prices compared to its sales of any big company — perfection is already expected.",
    teachingConcept: "Valuation (price vs. reality)",
  },
  {
    ticker: "TSM",
    name: "TSMC",
    sector: "Technology",
    category: "AI & Big Compute",
    productsBlurb: "You'll never see its name on a product, but it manufactures the chips inside iPhones, PlayStations, and NVIDIA AI cards.",
    howMoneyBlurb: "Runs the world's most advanced chip factories and gets paid by Apple, NVIDIA, and AMD to make their designs real.",
    bullBlurb: "Almost every advanced chip on Earth is made by TSMC — the whole tech world lines up at its door.",
    bearBlurb: "Its most important factories are in Taiwan, so world politics is a real risk, and new factories cost tens of billions.",
    teachingConcept: "Chokepoints (when everyone needs you)",
  },
];

/** SPY is seeded as a non-draftable benchmark for the robot rival. */
export const BENCHMARK: UniverseStock = {
  ticker: "SPY",
  name: "S&P 500 (SPY)",
  sector: "Index",
  category: "Benchmark",
  productsBlurb: "A tiny slice of the 500 biggest companies in America, all in one share.",
  howMoneyBlurb: "Tracks the S&P 500 index — when big American companies do well, SPY does well.",
  bullBlurb: "Owning everything means never missing the winners.",
  bearBlurb: "You also own the losers, and you will never beat the market — you ARE the market.",
  teachingConcept: "Index investing",
  isBenchmark: true,
};
